//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.03 at 12:11:11 AM CST 
//


package com.springboot.productservice.wsdl;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.springboot.productservice.wsdl package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetAllOrdersOfCustomerRequest_QNAME = new QName("http://productservices.com/ProductsServicesOpertions", "getAllOrdersOfCustomerRequest");
    private final static QName _GetAllOrdersOfCustomerResponse_QNAME = new QName("http://productservices.com/ProductsServicesOpertions", "getAllOrdersOfCustomerResponse");
    private final static QName _GetAllProductsRequest_QNAME = new QName("http://productservices.com/ProductsServicesOpertions", "getAllProductsRequest");
    private final static QName _GetAllProductsResponse_QNAME = new QName("http://productservices.com/ProductsServicesOpertions", "getAllProductsResponse");
    private final static QName _GetOrderByIdRequest_QNAME = new QName("http://productservices.com/ProductsServicesOpertions", "getOrderByIdRequest");
    private final static QName _GetOrderByIdResponse_QNAME = new QName("http://productservices.com/ProductsServicesOpertions", "getOrderByIdResponse");
    private final static QName _GetfilteredProductRequest_QNAME = new QName("http://productservices.com/ProductsServicesOpertions", "getfilteredProductRequest");
    private final static QName _GetfilteredProductResponse_QNAME = new QName("http://productservices.com/ProductsServicesOpertions", "getfilteredProductResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.springboot.productservice.wsdl
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Orders }
     * 
     */
    public Orders createOrders() {
        return new Orders();
    }

    /**
     * Create an instance of {@link Products }
     * 
     */
    public Products createProducts() {
        return new Products();
    }

    /**
     * Create an instance of {@link GetAllOrdersOfCustomerRequest }
     * 
     */
    public GetAllOrdersOfCustomerRequest createGetAllOrdersOfCustomerRequest() {
        return new GetAllOrdersOfCustomerRequest();
    }

    /**
     * Create an instance of {@link GetAllOrdersOfCustomerResponse }
     * 
     */
    public GetAllOrdersOfCustomerResponse createGetAllOrdersOfCustomerResponse() {
        return new GetAllOrdersOfCustomerResponse();
    }

    /**
     * Create an instance of {@link GetAllProductsRequest }
     * 
     */
    public GetAllProductsRequest createGetAllProductsRequest() {
        return new GetAllProductsRequest();
    }

    /**
     * Create an instance of {@link GetAllProductsResponse }
     * 
     */
    public GetAllProductsResponse createGetAllProductsResponse() {
        return new GetAllProductsResponse();
    }

    /**
     * Create an instance of {@link GetOrderByIdRequest }
     * 
     */
    public GetOrderByIdRequest createGetOrderByIdRequest() {
        return new GetOrderByIdRequest();
    }

    /**
     * Create an instance of {@link GetOrderByIdResponse }
     * 
     */
    public GetOrderByIdResponse createGetOrderByIdResponse() {
        return new GetOrderByIdResponse();
    }

    /**
     * Create an instance of {@link GetfilteredProductRequest }
     * 
     */
    public GetfilteredProductRequest createGetfilteredProductRequest() {
        return new GetfilteredProductRequest();
    }

    /**
     * Create an instance of {@link GetfilteredProductResponse }
     * 
     */
    public GetfilteredProductResponse createGetfilteredProductResponse() {
        return new GetfilteredProductResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllOrdersOfCustomerRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://productservices.com/ProductsServicesOpertions", name = "getAllOrdersOfCustomerRequest")
    public JAXBElement<GetAllOrdersOfCustomerRequest> createGetAllOrdersOfCustomerRequest(GetAllOrdersOfCustomerRequest value) {
        return new JAXBElement<GetAllOrdersOfCustomerRequest>(_GetAllOrdersOfCustomerRequest_QNAME, GetAllOrdersOfCustomerRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllOrdersOfCustomerResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://productservices.com/ProductsServicesOpertions", name = "getAllOrdersOfCustomerResponse")
    public JAXBElement<GetAllOrdersOfCustomerResponse> createGetAllOrdersOfCustomerResponse(GetAllOrdersOfCustomerResponse value) {
        return new JAXBElement<GetAllOrdersOfCustomerResponse>(_GetAllOrdersOfCustomerResponse_QNAME, GetAllOrdersOfCustomerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllProductsRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://productservices.com/ProductsServicesOpertions", name = "getAllProductsRequest")
    public JAXBElement<GetAllProductsRequest> createGetAllProductsRequest(GetAllProductsRequest value) {
        return new JAXBElement<GetAllProductsRequest>(_GetAllProductsRequest_QNAME, GetAllProductsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllProductsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://productservices.com/ProductsServicesOpertions", name = "getAllProductsResponse")
    public JAXBElement<GetAllProductsResponse> createGetAllProductsResponse(GetAllProductsResponse value) {
        return new JAXBElement<GetAllProductsResponse>(_GetAllProductsResponse_QNAME, GetAllProductsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOrderByIdRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://productservices.com/ProductsServicesOpertions", name = "getOrderByIdRequest")
    public JAXBElement<GetOrderByIdRequest> createGetOrderByIdRequest(GetOrderByIdRequest value) {
        return new JAXBElement<GetOrderByIdRequest>(_GetOrderByIdRequest_QNAME, GetOrderByIdRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetOrderByIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://productservices.com/ProductsServicesOpertions", name = "getOrderByIdResponse")
    public JAXBElement<GetOrderByIdResponse> createGetOrderByIdResponse(GetOrderByIdResponse value) {
        return new JAXBElement<GetOrderByIdResponse>(_GetOrderByIdResponse_QNAME, GetOrderByIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetfilteredProductRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://productservices.com/ProductsServicesOpertions", name = "getfilteredProductRequest")
    public JAXBElement<GetfilteredProductRequest> createGetfilteredProductRequest(GetfilteredProductRequest value) {
        return new JAXBElement<GetfilteredProductRequest>(_GetfilteredProductRequest_QNAME, GetfilteredProductRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetfilteredProductResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://productservices.com/ProductsServicesOpertions", name = "getfilteredProductResponse")
    public JAXBElement<GetfilteredProductResponse> createGetfilteredProductResponse(GetfilteredProductResponse value) {
        return new JAXBElement<GetfilteredProductResponse>(_GetfilteredProductResponse_QNAME, GetfilteredProductResponse.class, null, value);
    }

}
