//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.03 at 12:11:11 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://productservices.com/ProductsServicesOpertions", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.springboot.productservice.wsdl;
