//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.02 at 10:02:27 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://productservices.com/ProductsServicesOpertions", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.productservices.productsservicesopertions;
